@startmindmap
* root
** 0
*** 6
**** 1
***** 2
****** 3
******* 4
******** 5
********* 6
********** 7
*********** 8 (Alice)
**** 8
***** 7
****** 6
******* 5
******** 4
********* 3
********** 2
*********** 1 (Diana)
**** 9
***** 8
****** 7
******* 6
******** 5
********* 4
********** 3
*********** 2 (Bob)
*** 7
**** 1
***** 2
****** 3
******* 4
******** 5
********* 6
********** 7
*********** 8 (Charlie)
** 1
*** 1
**** 2 (Urgences Europeennes)
**** 5 (SDF - Sans Abri)
**** 6
***** 1
****** 1
******* 7 (Medecin de Garde)
**** 9 (Enfance en Danger)
*** 5 (SAMU)
*** 7 (Police)
*** 8 (Pompiers)
*** 9
**** 1 (Secours Aeronautique)
**** 6 (Secours Maritime)
**** 7 (Alerte Attentat)
** 3
*** 1
**** 1
***** 4 (Prevention Suicide)
@endmindmap
